export const InventoryData = [
  {
    id: 1,
    productName: "iPhone 13",
    productCode: "IPH13-001",
    quantityInStock: 10,
    unitPrice: 999,
    supplier: "Apple Inc.",
    expiryDate: null,
    category: "Electronics",
    location: "Warehouse A",
    dateAdded: "2023-01-01",
    lastUpdated: "2023-04-20",
  },
  {
    id: 2,
    productName: "Samsung Galaxy S21",
    productCode: "S21-002",
    quantityInStock: 200,
    unitPrice: 899,
    supplier: "Samsung Electronics",
    expiryDate: null,
    category: "Electronics",
    location: "Warehouse A",
    dateAdded: "2023-01-05",
    lastUpdated: "2023-04-22",
  },
  {
    id: 3,
    productName: "Dell XPS 15 Laptop",
    productCode: "XPS15-003",
    quantityInStock: 100,
    unitPrice: 1499,
    supplier: "Dell Technologies",
    expiryDate: null,
    category: "Computers",
    location: "Warehouse B",
    dateAdded: "2023-02-10",
    lastUpdated: "2023-04-25",
  },
  {
    id: 4,
    productName: "Sony PlayStation 5",
    productCode: "PS5-004",
    quantityInStock: 50,
    unitPrice: 499,
    supplier: "Sony Corporation",
    expiryDate: null,
    category: "Electronics",
    location: "Warehouse C",
    dateAdded: "2023-02-15",
    lastUpdated: "2023-04-23",
  },
  {
    id: 5,
    productName: "Nike Air Max 270",
    productCode: "AM270-005",
    quantityInStock: 300,
    unitPrice: 150,
    supplier: "Nike, Inc.",
    expiryDate: null,
    category: "Footwear",
    location: "Warehouse D",
    dateAdded: "2023-03-01",
    lastUpdated: "2023-04-21",
  },
  {
    id: 6,
    productName: "Apple AirPods Pro",
    productCode: "APPRO-006",
    quantityInStock: 120,
    unitPrice: 249,
    supplier: "Apple Inc.",
    expiryDate: null,
    category: "Electronics",
    location: "Warehouse A",
    dateAdded: "2023-03-05",
    lastUpdated: "2023-04-24",
  },
  {
    id: 7,
    productName: "Canon EOS R5 Camera",
    productCode: "EOSR5-007",
    quantityInStock: 80,
    unitPrice: 3899,
    supplier: "Canon Inc.",
    expiryDate: null,
    category: "Cameras",
    location: "Warehouse E",
    dateAdded: "2023-03-10",
    lastUpdated: "2023-04-26",
  },
  {
    id: 8,
    productName: "Samsung 65-inch QLED TV",
    productCode: "QLED65-008",
    quantityInStock: 60,
    unitPrice: 1799,
    supplier: "Samsung Electronics",
    expiryDate: null,
    category: "Electronics",
    location: "Warehouse F",
    dateAdded: "2023-04-01",
    lastUpdated: "2023-04-27",
  },
  {
    id: 9,
    productName: "Amazon Kindle Paperwhite",
    productCode: "KINDLE-009",
    quantityInStock: 90,
    unitPrice: 129,
    supplier: "Amazon.com, Inc.",
    expiryDate: null,
    category: "Electronics",
    location: "Warehouse G",
    dateAdded: "2023-04-05",
    lastUpdated: "2023-04-28",
  },
  {
    id: 10,
    productName: "Fitbit Versa 3 Smartwatch",
    productCode: "FITVS3-010",
    quantityInStock: 150,
    unitPrice: 229,
    supplier: "Fitbit, Inc.",
    expiryDate: null,
    category: "Wearables",
    location: "Warehouse H",
    dateAdded: "2023-04-10",
    lastUpdated: "2023-04-29",
  },
  {
    id: 11,
    productName: "Microsoft Surface Pro 7",
    productCode: "SURPRO7-011",
    quantityInStock: 70,
    unitPrice: 899,
    supplier: "Microsoft Corporation",
    expiryDate: null,
    category: "Computers",
    location: "Warehouse B",
    dateAdded: "2023-05-01",
    lastUpdated: "2023-05-02",
  },
  {
    id: 12,
    productName: "LEGO Star Wars Millennium Falcon",
    productCode: "MILFALC-012",
    quantityInStock: 40,
    unitPrice: 159.99,
    supplier: "LEGO Group",
    expiryDate: null,
    category: "Toys",
    location: "Warehouse I",
    dateAdded: "2023-05-05",
    lastUpdated: "2023-05-03",
  },
  {
    id: 13,
    productName: "Instant Pot Duo Plus 9-in-1",
    productCode: "IPDUO9-013",
    quantityInStock: 120,
    unitPrice: 119.95,
    supplier: "Instant Brands Inc.",
    expiryDate: null,
    category: "Home Appliances",
    location: "Warehouse J",
    dateAdded: "2023-05-10",
    lastUpdated: "2023-05-04",
  },
  {
    id: 14,
    productName: "Fujifilm Instax Mini 11",
    productCode: "INSTAX11-014",
    quantityInStock: 100,
    unitPrice: 69.95,
    supplier: "Fujifilm Holdings Corporation",
    expiryDate: null,
    category: "Cameras",
    location: "Warehouse E",
    dateAdded: "2023-05-15",
    lastUpdated: "2023-05-05",
  },
  {
    id: 15,
    productName: "KitchenAid Artisan Stand Mixer",
    productCode: "KASM-015",
    quantityInStock: 80,
    unitPrice: 379,
    supplier: "Whirlpool Corporation",
    expiryDate: null,
    category: "Kitchen Appliances",
    location: "Warehouse K",
    dateAdded: "2023-05-20",
    lastUpdated: "2023-05-06",
  },
  {
    id: 16,
    productName: "Bose QuietComfort 35 II Headphones",
    productCode: "QC35II-016",
    quantityInStock: 100,
    unitPrice: 299,
    supplier: "Bose Corporation",
    expiryDate: null,
    category: "Electronics",
    location: "Warehouse A",
    dateAdded: "2023-05-25",
    lastUpdated: "2023-05-07",
  },
  {
    id: 17,
    productName: "Google Nest Hub (2nd Gen)",
    productCode: "NESTHUB-017",
    quantityInStock: 150,
    unitPrice: 99.99,
    supplier: "Google LLC",
    expiryDate: null,
    category: "Electronics",
    location: "Warehouse L",
    dateAdded: "2023-06-01",
    lastUpdated: "2023-05-08",
  },
  {
    id: 18,
    productName: "Yeti Rambler 20 oz Tumbler",
    productCode: "RAMBLER-018",
    quantityInStock: 200,
    unitPrice: 29.99,
    supplier: "YETI Holdings, Inc.",
    expiryDate: null,
    category: "Outdoor Gear",
    location: "Warehouse M",
    dateAdded: "2023-06-05",
    lastUpdated: "2023-05-09",
  },
  {
    id: 19,
    productName: "GoPro HERO9 Black",
    productCode: "HERO9-019",
    quantityInStock: 60,
    unitPrice: 399.99,
    supplier: "GoPro, Inc.",
    expiryDate: null,
    category: "Cameras",
    location: "Warehouse E",
    dateAdded: "2023-06-10",
    lastUpdated: "2023-05-10",
  },
  {
    id: 20,
    productName: "Anker PowerCore 20000mAh Portable Charger",
    productCode: "PC20000-020",
    quantityInStock: 150,
    unitPrice: 49.99,
    supplier: "Anker Innovations",
    expiryDate: null,
    category: "Electronics",
    location: "Warehouse A",
    dateAdded: "2023-06-15",
    lastUpdated: "2023-05-11",
  },
];
